image: php:7.2-cli

before_script:
  - apt-get update
  - apt-get install zip unzip sqlite3 libsqlite3-dev -y
  # Install composer and PHP project dependencies
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar install
  - php composer.phar run post-root-package-install
  - php composer.phar run post-create-project-cmd

test_php:
  script:
    - vendor/bin/parallel-lint --exclude vendor .
    - vendor/bin/phpunit
